# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170430_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='statics/images/default.jpg', upload_to='photos'),
        ),
    ]
