# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170501_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lastarticle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='nextarticle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='lastarticle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='photos/'),
        ),
    ]
