# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170504_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='lastarticle',
            new_name='newarticle',
        ),
    ]
