# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170505_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='newarticle',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
