# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170505_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='newarticle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
