# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170506_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='statics/images/default.jpg', upload_to='photos/'),
        ),
    ]
