# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170518_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
