# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170518_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='home.Tag'),
        ),
    ]
