# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170518_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='home.Tag'),
        ),
    ]
